; generated by PrusaSlicer 2.2.0+win64 on 2020-08-17 at 23:42:19 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R3
M73 Q0 S3
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm/sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
M862.3 P "MK3SMMU2S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.9.0 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
Tx
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling

;go outside print area
G1 Y-3.0 F1000.0
G1 Z0.4 F1000.0
; select extruder
Tc
; purge line
G1 X55.0 F2000.0
G1 Z0.3 F1000.0
G92 E0.0
G1 X240.0 E25.0 F2200.0
M73 Q4 S3
M73 P4 R3
G1 Y-2.0 F1000.0
G1 X55.0 E25 F1400.0
G1 Z0.20 F1000.0
G1 X5.0 E4.0 F1000.0

M221 S95
G92 E0.0
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.06 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


G1 E-0.80000 F2100.00000
G1 Z0.600 F10800.000
;AFTER_LAYER_CHANGE
;0.2
G1 X114.502 Y70.986
G1 Z0.200
G1 E0.80000 F2100.00000
M204 S1000
G1 F902
G1 X114.974 Y70.198 E0.02879
G1 X115.376 Y69.814 E0.01745
G1 X115.848 Y69.518 E0.01745
G1 X116.369 Y69.323 E0.01745
G1 X116.919 Y69.238 E0.01745
G1 X133.072 Y69.234 E0.50645
G1 X134.061 Y69.419 E0.03157
G1 X134.915 Y69.945 E0.03145
G1 X135.526 Y70.746 E0.03157
G1 X135.808 Y71.709 E0.03145
G1 X135.820 Y88.086 E0.51350
G1 X135.635 Y88.985 E0.02879
G1 X135.161 Y89.777 E0.02892
G1 X134.736 Y90.179 E0.01835
G1 X134.239 Y90.480 E0.01822
G1 X133.686 Y90.671 E0.01835
G1 X133.109 Y90.742 E0.01822
G1 X116.965 Y90.740 E0.50619
G1 X116.066 Y90.553 E0.02879
G1 X115.278 Y90.081 E0.02879
G1 X114.876 Y89.656 E0.01835
G1 X114.575 Y89.159 E0.01822
G1 X114.384 Y88.606 E0.01835
G1 X114.314 Y88.029 E0.01822
G1 X114.315 Y71.885 E0.50619
G1 X114.490 Y71.045 E0.02691
G1 F8640.000
G1 X114.974 Y70.198 E-0.22514
G1 X115.376 Y69.814 E-0.12853
G1 X115.848 Y69.518 E-0.12853
G1 X116.369 Y69.323 E-0.12853
G1 X116.919 Y69.238 E-0.12853
G1 X117.009 Y69.237 E-0.02073
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
G1 X116.036 Y69.846
G1 Z0.200
G1 E0.80000 F2100.00000
G1 F902
G1 X116.960 Y69.613 E0.02989
G1 X133.071 Y69.611 E0.50516
G1 X133.928 Y69.772 E0.02731
G1 X134.671 Y70.233 E0.02743
G1 X135.197 Y70.932 E0.02743
G1 X135.435 Y71.774 E0.02743
G1 X135.443 Y88.064 E0.51077
G1 X135.280 Y88.858 E0.02543
G1 X134.861 Y89.548 E0.02532
G1 X134.496 Y89.888 E0.01562
G1 X134.065 Y90.145 E0.01574
G1 X133.594 Y90.306 E0.01562
G1 X133.095 Y90.365 E0.01574
G1 X116.988 Y90.363 E0.50505
G1 X116.197 Y90.200 E0.02532
G1 X115.507 Y89.781 E0.02532
G1 X115.168 Y89.416 E0.01562
G1 X114.910 Y88.985 E0.01574
G1 X114.749 Y88.514 E0.01562
G1 X114.691 Y88.015 E0.01574
G1 X114.692 Y71.908 E0.50505
G1 X114.856 Y71.117 E0.02532
G1 X115.275 Y70.427 E0.02532
G1 X115.988 Y69.883 E0.02813
G1 F8640.000
G1 X116.960 Y69.613 E-0.23293
G1 X119.243 Y69.613 E-0.52707
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
G1 X117.358 Y72.278
G1 Z0.200
G1 E0.80000 F2100.00000
G1 F902
G1 X132.778 Y72.278 E0.48348
G1 X132.778 Y87.698 E0.48348
G1 X117.358 Y87.698 E0.48348
G1 X117.358 Y72.338 E0.48160
G1 X117.254 Y71.891 F10800.000
G1 X117.278 Y72.338
G1 F902
G1 X117.278 Y72.198 E0.00439
G1 X132.858 Y72.198 E0.48850
G1 X132.858 Y87.778 E0.48850
G1 X117.278 Y87.778 E0.48850
G1 X117.278 Y72.398 E0.48223
G1 X117.376 Y72.239 F10800.000
M106 S255
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.35


G1 F8640.000
G1 X117.278 Y72.198 E-0.04618
G1 X120.369 Y72.198 E-0.71382
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
;AFTER_LAYER_CHANGE
;0.35
G1 X114.502 Y70.986
G1 Z0.350
G1 E0.80000 F2100.00000
G1 F900
G1 X114.974 Y70.198 E0.02221
G1 X115.376 Y69.814 E0.01346
G1 X115.848 Y69.518 E0.01346
G1 X116.369 Y69.323 E0.01346
G1 X116.919 Y69.238 E0.01346
G1 X133.072 Y69.234 E0.39064
G1 X134.061 Y69.419 E0.02435
G1 X134.915 Y69.945 E0.02426
G1 X135.526 Y70.746 E0.02435
G1 X135.808 Y71.709 E0.02426
G1 X135.820 Y88.086 E0.39609
G1 X135.635 Y88.985 E0.02221
G1 X135.161 Y89.777 E0.02230
G1 X134.736 Y90.179 E0.01415
G1 X134.239 Y90.480 E0.01405
G1 X133.686 Y90.671 E0.01415
G1 X133.109 Y90.742 E0.01405
G1 X116.965 Y90.740 E0.39045
G1 X116.066 Y90.553 E0.02221
G1 X115.278 Y90.081 E0.02221
G1 X114.876 Y89.656 E0.01415
G1 X114.575 Y89.159 E0.01405
G1 X114.384 Y88.606 E0.01415
G1 X114.314 Y88.029 E0.01405
G1 X114.315 Y71.885 E0.39045
G1 X114.490 Y71.045 E0.02076
G1 F8640.000
G1 X114.974 Y70.198 E-0.22514
G1 X115.376 Y69.814 E-0.12853
G1 X115.848 Y69.518 E-0.12853
G1 X116.369 Y69.323 E-0.12853
G1 X116.919 Y69.238 E-0.12853
G1 X117.009 Y69.237 E-0.02073
G1 E-0.04000 F2100.00000
G1 Z0.950 F10800.000
G1 X116.036 Y69.846
G1 Z0.350
G1 E0.80000 F2100.00000
G1 F900
G1 X116.960 Y69.613 E0.02306
G1 X133.071 Y69.611 E0.38965
G1 X133.928 Y69.772 E0.02107
G1 X134.671 Y70.233 E0.02116
G1 X135.197 Y70.932 E0.02116
G1 X135.435 Y71.774 E0.02116
G1 X135.443 Y88.064 E0.39398
G1 X135.280 Y88.858 E0.01962
G1 X134.861 Y89.548 E0.01953
G1 X134.496 Y89.888 E0.01205
G1 X134.065 Y90.145 E0.01214
G1 X133.594 Y90.306 E0.01205
G1 X133.095 Y90.365 E0.01214
G1 X116.988 Y90.363 E0.38956
G1 X116.197 Y90.200 E0.01953
G1 X115.507 Y89.781 E0.01953
G1 X115.168 Y89.416 E0.01205
G1 X114.910 Y88.985 E0.01214
G1 X114.749 Y88.514 E0.01205
G1 X114.691 Y88.015 E0.01214
G1 X114.692 Y71.908 E0.38956
G1 X114.856 Y71.117 E0.01953
G1 X115.275 Y70.427 E0.01953
G1 X115.988 Y69.883 E0.02170
G1 F8640.000
G1 X116.960 Y69.613 E-0.23293
G1 X119.243 Y69.613 E-0.52707
G1 E-0.04000 F2100.00000
G1 Z0.950 F10800.000
G1 X117.343 Y72.263
G1 Z0.350
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X132.793 Y72.263 E0.40256
G1 X132.793 Y87.713 E0.40256
G1 X117.343 Y87.713 E0.40256
G1 X117.343 Y72.323 E0.40100
M204 S1000
G1 X117.239 Y71.876 F10800.000
G1 X117.293 Y72.323
M204 S800
G1 F900
G1 X117.293 Y72.213 E0.00287
G1 X132.843 Y72.213 E0.40517
G1 X132.843 Y87.763 E0.40517
G1 X117.293 Y87.763 E0.40517
G1 X117.293 Y72.383 E0.40074
M204 S1000
G1 X117.370 Y72.245 F10800.000
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.5


G1 F8640.000
G1 X117.293 Y72.213 E-0.03925
G1 X120.414 Y72.213 E-0.72075
G1 E-0.04000 F2100.00000
G1 Z0.950 F10800.000
;AFTER_LAYER_CHANGE
;0.5
G1 X114.502 Y70.986
G1 Z0.500
G1 E0.80000 F2100.00000
G1 F900
G1 X114.974 Y70.198 E0.02221
G1 X115.376 Y69.814 E0.01346
G1 X115.848 Y69.518 E0.01346
G1 X116.369 Y69.323 E0.01346
G1 X116.919 Y69.238 E0.01346
G1 X133.072 Y69.234 E0.39064
G1 X134.061 Y69.419 E0.02435
G1 X134.915 Y69.945 E0.02426
G1 X135.526 Y70.746 E0.02435
G1 X135.808 Y71.709 E0.02426
G1 X135.820 Y88.086 E0.39609
G1 X135.635 Y88.985 E0.02221
G1 X135.161 Y89.777 E0.02230
G1 X134.736 Y90.179 E0.01415
G1 X134.239 Y90.480 E0.01405
G1 X133.686 Y90.671 E0.01415
G1 X133.109 Y90.742 E0.01405
G1 X116.965 Y90.740 E0.39045
G1 X116.066 Y90.553 E0.02221
G1 X115.278 Y90.081 E0.02221
G1 X114.876 Y89.656 E0.01415
G1 X114.575 Y89.159 E0.01405
G1 X114.384 Y88.606 E0.01415
G1 X114.314 Y88.029 E0.01405
G1 X114.315 Y71.885 E0.39045
G1 X114.490 Y71.045 E0.02076
G1 F8640.000
G1 X114.974 Y70.198 E-0.22514
G1 X115.376 Y69.814 E-0.12853
G1 X115.848 Y69.518 E-0.12853
G1 X116.369 Y69.323 E-0.12853
G1 X116.919 Y69.238 E-0.12853
G1 X117.009 Y69.237 E-0.02073
G1 E-0.04000 F2100.00000
G1 Z1.100 F10800.000
G1 X116.036 Y69.846
G1 Z0.500
G1 E0.80000 F2100.00000
G1 F900
G1 X116.960 Y69.613 E0.02306
G1 X133.071 Y69.611 E0.38965
M73 Q38 S2
G1 X133.928 Y69.772 E0.02107
G1 X134.671 Y70.233 E0.02116
G1 X135.197 Y70.932 E0.02116
G1 X135.435 Y71.774 E0.02116
M73 P38 R2
G1 X135.443 Y88.064 E0.39398
G1 X135.280 Y88.858 E0.01962
G1 X134.861 Y89.548 E0.01953
G1 X134.496 Y89.888 E0.01205
G1 X134.065 Y90.145 E0.01214
G1 X133.594 Y90.306 E0.01205
G1 X133.095 Y90.365 E0.01214
G1 X116.988 Y90.363 E0.38956
G1 X116.197 Y90.200 E0.01953
G1 X115.507 Y89.781 E0.01953
G1 X115.168 Y89.416 E0.01205
G1 X114.910 Y88.985 E0.01214
G1 X114.749 Y88.514 E0.01205
G1 X114.691 Y88.015 E0.01214
G1 X114.692 Y71.908 E0.38956
G1 X114.856 Y71.117 E0.01953
G1 X115.275 Y70.427 E0.01953
G1 X115.988 Y69.883 E0.02170
G1 F8640.000
G1 X116.960 Y69.613 E-0.23293
G1 X119.243 Y69.613 E-0.52707
G1 E-0.04000 F2100.00000
G1 Z1.100 F10800.000
G1 X117.343 Y72.263
G1 Z0.500
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X132.793 Y72.263 E0.40256
G1 X132.793 Y87.713 E0.40256
G1 X117.343 Y87.713 E0.40256
G1 X117.343 Y72.323 E0.40100
M204 S1000
G1 X117.239 Y71.876 F10800.000
G1 X117.293 Y72.323
M204 S800
G1 F900
G1 X117.293 Y72.213 E0.00287
G1 X132.843 Y72.213 E0.40517
G1 X132.843 Y87.763 E0.40517
G1 X117.293 Y87.763 E0.40517
G1 X117.293 Y72.383 E0.40074
M204 S1000
G1 X117.370 Y72.245 F10800.000
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.65


G1 F8640.000
G1 X117.293 Y72.213 E-0.03925
G1 X120.414 Y72.213 E-0.72075
G1 E-0.04000 F2100.00000
G1 Z1.100 F10800.000
;AFTER_LAYER_CHANGE
;0.65
G1 X117.343 Y72.263
G1 Z0.650
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X132.793 Y72.263 E0.40256
G1 X132.793 Y87.713 E0.40256
G1 X117.343 Y87.713 E0.40256
G1 X117.343 Y72.323 E0.40100
M204 S1000
G1 X117.239 Y71.876 F10800.000
G1 X117.293 Y72.323
M204 S800
G1 F900
G1 X117.293 Y72.213 E0.00287
G1 X132.843 Y72.213 E0.40517
G1 X132.843 Y87.763 E0.40517
G1 X117.293 Y87.763 E0.40517
G1 X117.293 Y72.383 E0.40074
M204 S1000
G1 X117.370 Y72.245 F10800.000
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.8


G1 F8640.000
G1 X117.293 Y72.213 E-0.03925
G1 X120.414 Y72.213 E-0.72075
G1 E-0.04000 F2100.00000
G1 Z1.250 F10800.000
;AFTER_LAYER_CHANGE
;0.8
G1 X117.343 Y72.263
G1 Z0.800
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X132.793 Y72.263 E0.40256
G1 X132.793 Y87.713 E0.40256
G1 X117.343 Y87.713 E0.40256
G1 X117.343 Y72.323 E0.40100
M204 S1000
G1 X117.239 Y71.876 F10800.000
G1 X117.293 Y72.323
M204 S800
G1 F900
G1 X117.293 Y72.213 E0.00287
G1 X132.843 Y72.213 E0.40517
G1 X132.843 Y87.763 E0.40517
G1 X117.293 Y87.763 E0.40517
G1 X117.293 Y72.383 E0.40074
M204 S1000
G1 X117.370 Y72.245 F10800.000
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.95


G1 F8640.000
G1 X117.293 Y72.213 E-0.03925
G1 X120.414 Y72.213 E-0.72075
G1 E-0.04000 F2100.00000
G1 Z1.400 F10800.000
;AFTER_LAYER_CHANGE
;0.95
G1 X117.343 Y72.263
G1 Z0.950
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X132.793 Y72.263 E0.40256
G1 X132.793 Y87.713 E0.40256
G1 X117.343 Y87.713 E0.40256
G1 X117.343 Y72.323 E0.40100
M204 S1000
G1 X117.239 Y71.876 F10800.000
G1 X117.293 Y72.323
M204 S800
G1 F900
G1 X117.293 Y72.213 E0.00287
G1 X132.843 Y72.213 E0.40517
G1 X132.843 Y87.763 E0.40517
G1 X117.293 Y87.763 E0.40517
G1 X117.293 Y72.383 E0.40074
M204 S1000
G1 X117.370 Y72.245 F10800.000
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.1


G1 F8640.000
G1 X117.293 Y72.213 E-0.03925
G1 X120.414 Y72.213 E-0.72075
G1 E-0.04000 F2100.00000
G1 Z1.550 F10800.000
;AFTER_LAYER_CHANGE
;1.1
G1 X117.343 Y72.263
G1 Z1.100
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X132.793 Y72.263 E0.40256
G1 X132.793 Y87.713 E0.40256
G1 X117.343 Y87.713 E0.40256
G1 X117.343 Y72.323 E0.40100
M204 S1000
G1 X117.239 Y71.876 F10800.000
G1 X117.293 Y72.323
M204 S800
G1 F900
G1 X117.293 Y72.213 E0.00287
G1 X132.843 Y72.213 E0.40517
G1 X132.843 Y87.763 E0.40517
G1 X117.293 Y87.763 E0.40517
G1 X117.293 Y72.383 E0.40074
M204 S1000
G1 X117.370 Y72.245 F10800.000
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.25


G1 F8640.000
G1 X117.293 Y72.213 E-0.03925
G1 X120.414 Y72.213 E-0.72075
G1 E-0.04000 F2100.00000
G1 Z1.700 F10800.000
;AFTER_LAYER_CHANGE
;1.25
G1 X117.343 Y72.263
G1 Z1.250
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X132.793 Y72.263 E0.40256
G1 X132.793 Y87.713 E0.40256
G1 X117.343 Y87.713 E0.40256
G1 X117.343 Y72.323 E0.40100
M204 S1000
G1 X117.239 Y71.876 F10800.000
G1 X117.293 Y72.323
M204 S800
G1 F900
G1 X117.293 Y72.213 E0.00287
G1 X132.843 Y72.213 E0.40517
G1 X132.843 Y87.763 E0.40517
G1 X117.293 Y87.763 E0.40517
G1 X117.293 Y72.383 E0.40074
M204 S1000
G1 X117.370 Y72.245 F10800.000
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.4


G1 F8640.000
G1 X117.293 Y72.213 E-0.03925
G1 X120.414 Y72.213 E-0.72075
G1 E-0.04000 F2100.00000
G1 Z1.850 F10800.000
;AFTER_LAYER_CHANGE
;1.4
G1 X117.343 Y72.263
G1 Z1.400
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X132.793 Y72.263 E0.40256
G1 X132.793 Y87.713 E0.40256
G1 X117.343 Y87.713 E0.40256
M73 Q73 S1
M73 P73 R1
G1 X117.343 Y72.323 E0.40100
M204 S1000
G1 X117.239 Y71.876 F10800.000
G1 X117.293 Y72.323
M204 S800
G1 F900
G1 X117.293 Y72.213 E0.00287
G1 X132.843 Y72.213 E0.40517
G1 X132.843 Y87.763 E0.40517
G1 X117.293 Y87.763 E0.40517
G1 X117.293 Y72.383 E0.40074
M204 S1000
G1 X117.370 Y72.245 F10800.000
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.55


G1 F8640.000
G1 X117.293 Y72.213 E-0.03925
G1 X120.414 Y72.213 E-0.72075
G1 E-0.04000 F2100.00000
G1 Z2.000 F10800.000
;AFTER_LAYER_CHANGE
;1.55
G1 X117.343 Y72.263
G1 Z1.550
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X132.793 Y72.263 E0.40256
G1 X132.793 Y87.713 E0.40256
G1 X117.343 Y87.713 E0.40256
G1 X117.343 Y72.323 E0.40100
M204 S1000
G1 X117.239 Y71.876 F10800.000
G1 X117.293 Y72.323
M204 S800
G1 F900
G1 X117.293 Y72.213 E0.00287
G1 X132.843 Y72.213 E0.40517
G1 X132.843 Y87.763 E0.40517
G1 X117.293 Y87.763 E0.40517
G1 X117.293 Y72.383 E0.40074
M204 S1000
G1 X117.370 Y72.245 F10800.000
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.7


G1 F8640.000
G1 X117.293 Y72.213 E-0.03925
G1 X120.414 Y72.213 E-0.72075
G1 E-0.04000 F2100.00000
G1 Z2.150 F10800.000
;AFTER_LAYER_CHANGE
;1.7
G1 X117.343 Y72.263
G1 Z1.700
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X132.793 Y72.263 E0.40256
G1 X132.793 Y87.713 E0.40256
G1 X117.343 Y87.713 E0.40256
G1 X117.343 Y72.323 E0.40100
M204 S1000
G1 X117.239 Y71.876 F10800.000
G1 X117.293 Y72.323
M204 S800
G1 F900
G1 X117.293 Y72.213 E0.00287
G1 X132.843 Y72.213 E0.40517
G1 X132.843 Y87.763 E0.40517
G1 X117.293 Y87.763 E0.40517
G1 X117.293 Y72.383 E0.40074
M204 S1000
G1 X117.370 Y72.245 F10800.000
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.85


G1 F8640.000
G1 X117.293 Y72.213 E-0.03925
G1 X120.414 Y72.213 E-0.72075
G1 E-0.04000 F2100.00000
G1 Z2.300 F10800.000
;AFTER_LAYER_CHANGE
;1.85
G1 X117.343 Y72.263
G1 Z1.850
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X132.793 Y72.263 E0.40256
G1 X132.793 Y87.713 E0.40256
G1 X117.343 Y87.713 E0.40256
G1 X117.343 Y72.323 E0.40100
M204 S1000
G1 X117.239 Y71.876 F10800.000
G1 X117.293 Y72.323
M204 S800
G1 F900
G1 X117.293 Y72.213 E0.00287
G1 X132.843 Y72.213 E0.40517
G1 X132.843 Y87.763 E0.40517
G1 X117.293 Y87.763 E0.40517
G1 X117.293 Y72.383 E0.40074
M204 S1000
G1 X117.370 Y72.245 F10800.000
;BEFORE_LAYER_CHANGE
G92 E0.0
;2


G1 F8640.000
G1 X117.293 Y72.213 E-0.03925
G1 X120.414 Y72.213 E-0.72075
G1 E-0.04000 F2100.00000
G1 Z2.450 F10800.000
;AFTER_LAYER_CHANGE
;2
G1 X117.343 Y72.263
G1 Z2.000
G1 E0.80000 F2100.00000
M204 S800
G1 F900
G1 X132.793 Y72.263 E0.40256
G1 X132.793 Y87.713 E0.40256
G1 X117.343 Y87.713 E0.40256
G1 X117.343 Y72.323 E0.40100
M204 S1000
G1 X117.239 Y71.876 F10800.000
G1 X117.293 Y72.323
M204 S800
G1 F900
G1 X117.293 Y72.213 E0.00287
G1 X132.843 Y72.213 E0.40517
G1 X132.843 Y87.763 E0.40517
G1 X117.293 Y87.763 E0.40517
G1 X117.293 Y72.383 E0.40074
M204 S1000
G1 X117.370 Y72.245 F10800.000
G1 F8640.000;_WIPE
G1 X117.293 Y72.213 E-0.03925
G1 F8640.000;_WIPE
G1 X120.414 Y72.213 E-0.72075
G1 E-0.04000 F2100.00000
G1 Z2.600 F10800.000
M107
; Filament-specific end gcode
G1 Z12.6 F720 ; Move print head up
G1 X0 Y210 F7200
G1 E2 F5000
G1 E2 F5500
G1 E2 F6000
G1 E-15.0000 F5800
G1 E-20.0000 F5500
G1 E10.0000 F3000
G1 E-10.0000 F3100
G1 E10.0000 F3150
G1 E-10.0000 F3250
G1 E10.0000 F3300

M140 S0 ; turn off heatbed
M107 ; turn off fan
M702 C
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA
M104 S0 ; turn off temperature
M84 ; disable motors
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 55.4
; filament used [cm3] = 0.1
; filament used [g] = 0.2
; filament cost = 0.0

; total filament used [g] = 0.2
; total filament cost = 0.0
; estimated printing time (normal mode) = 2m 52s
; estimated printing time (silent mode) = 2m 52s

; avoid_crossing_perimeters = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = rectilinear
; bottom_solid_layers = 5
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.8
; bridge_speed = 30
; brim_width = 0
; clip_multipart_objects = 1
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 20
; cooling_tube_retraction = 40
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = {if layer_z < max_print_height}G1 Z{z_offset+min(layer_z+10, max_print_height)}{endif} F720 ; Move print head up\nG1 X0 Y210 F7200\nG1 E2 F5000\nG1 E2 F5500\nG1 E2 F6000\nG1 E-15.0000 F5800\nG1 E-20.0000 F5500\nG1 E10.0000 F3000\nG1 E-10.0000 F3100\nG1 E10.0000 F3150\nG1 E-10.0000 F3250\nG1 E10.0000 F3300\n\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM702 C\nG4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\nM104 S0 ; turn off temperature\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extra_loading_move = -25
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 24.99
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Prusament PLA"
; filament_soluble = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Prusa Polymers
; fill_angle = 45
; fill_density = 100%
; fill_pattern = rectilinear
; first_layer_acceleration = 1000
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_temperature = 215
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 0
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.15
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_speed = 0
; min_fan_speed = 100
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; overhangs = 0
; parking_pos_retraction = 85
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 45
; perimeters = 2
; post_process = 
; print_settings_id = 0.15mm QUALITY @MK3
; printer_model = MK3SMMU2S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S MMU2S Single
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 3
; retract_lift = 0.6
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = nearest
; serial_port = 
; serial_speed = 250000
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 20
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.6}0.04{else}0.06{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{else}M900 K30{endif} ; Filament gcode LA 1.0"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.9.0 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nTx\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\n\n;go outside print area\nG1 Y-3.0 F1000.0\nG1 Z0.4 F1000.0\n; select extruder\nTc\n; purge line\nG1 X55.0 F2000.0\nG1 Z0.3 F1000.0\nG92 E0.0\nG1 X240.0 E25.0 F2200.0\nG1 Y-2.0 F1000.0\nG1 X55.0 E25 F1400.0\nG1 Z0.20 F1000.0\nG1 X5.0 E4.0 F1000.0\n\nM221 S{if layer_height<0.075}100{else}95{endif}\nG92 E0.0\n
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.1
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; temperature = 215
; thin_walls = 0
; threads = 4
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = rectilinear
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 40
; top_solid_layers = 7
; top_solid_min_thickness = 0.6
; travel_speed = 180
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
